/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

import com.example.client.Client;
import org.junit.Test;
import static org.junit.Assert.*;

public class ClientTest {
    @Test public void testAppBuilds() {
        Client classUnderTest = new Client();
        assertNotNull(classUnderTest);
    }
}
