/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.lib;

import org.junit.Test;

import java.time.LocalDate;

import static org.junit.Assert.*;

public class VirusTest {
    @Test
    public void testSomeLibraryMethod() {
        Virus classUnderTest = new Virus("Severe acute respiratory syndrome coronavirus 2",
                                         "SARS‑CoV‑2", LocalDate.parse("2019-12-30"));
        assertNotNull(classUnderTest);
    }
}
